import Profile from "@/components/core/profile";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Marlon Martin — Info",
  description: "Generated by create next app",
};

export default function Info() {
  return (
    <main className="mt-[4.5rem]">
      <Profile />
    </main>
  );
}
