import { Metadata } from "next";
import React, { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Marlon Martin — Works",
  description: "Generated by create next app",
};

export default function WorksLayout({ children }: { children: ReactNode }) {
  return <main className="p-4">{children}</main>;
}
