import { Metadata } from "next";
import React, { ReactNode, Suspense } from "react";

export const metadata: Metadata = {
  title: "Marlon Martin — Works",
  description: "Generated by create next app",
};

export default function WorksLayout({ children }: { children: ReactNode }) {
  return (
    <Suspense>
      <main className="p-4">{children}</main>
    </Suspense>
  );
}
