import type { Metadata } from "next";
import "lenis/dist/lenis.css";
import "./globals.css";
import Header from "./_components/header";
import Cursor from "@/components/ui/cursor";
import { ReactLenis } from "@/lib/lenis";

export const metadata: Metadata = {
  title: "Marlon Martin — Software Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis options={{ wheelMultiplier: 0.7, syncTouch: true }} root>
        <body className={`antialiased`}>
          <Header />
          {children}
          <Cursor />
        </body>
      </ReactLenis>
    </html>
  );
}
