import { workItems } from "@/utils/constants";
import WorkView from "../_components/work-view";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Marlon Martin — Work",
  description: "Generated by create next app",
};

export default async function WorkOverview({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const work_id = (await params).id;
  const work = workItems.filter((item) => item.id === work_id);

  return <WorkView work={work[0]} />;
}
